### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#1]
I manage multiple Twitter accounts, so would be nice to be able to easily switch between them.

Like [Twitcher](https://chrome.google.com/webstore/detail/twitcher-twitter-account/gmngpagflejjoblmmamaonmnkghjmebh) but without the donation request spam.

**Comment by FlyteWizard** [comment]
Would you be wanting something like the mobile twitter app has for multiple accounts?

**Comment by sindresorhus** [comment]
Yes, see `Twitcher` for how it could be implemented visually. The actual implementation would be to just record the login cookie when you log into a new account and when you click a different avatar to switch account, replace the current cookie with the correct stored one.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
