### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by dumitruaxentii** [sindresorhus/refined-twitter#10]
It is possible to have a dark mode to your extension? That would be awesome!

**Comment by sindresorhus** [comment]
Twitter already has a native dark mode: 

<img width="446" alt="screen shot 2017-12-07 at 22 02 17 2" src="https://user-images.githubusercontent.com/170270/33738691-63bbf6e4-db9a-11e7-8cf1-21e7b6fbedc3.png">

**Comment by dumitruaxentii** [comment]
Thanks! Love it!
