### ISSUE TITLE
Profile Image moves with scrolling

### ISSUE THREAD

**Issue by drepram** [sindresorhus/refined-twitter#102]
![screen shot 2018-04-21 at 21 32 08](https://user-images.githubusercontent.com/34530026/39241580-9d91980e-48b1-11e8-8101-07191ac7c13b.png)
> Profile image comes down as I'm scrolling through the pages

**Comment by filipekiss** [comment]
The header was purposefully remove on a8403f5fe, this is not a bug.

**Comment by drepram** [comment]
What about the profile image?

Is it supposed to come down as I'm scrolling through the page?

**Comment by filipekiss** [comment]
It shouldn't. I tried but wasn't able to reproduce. Can you post browser version and extension version so I can take a look? I'll re-open this until the image profile issue is cleared

**Comment by drepram** [comment]
Seems like the bug has been patched. Never mind.

**Comment by drepram** [comment]
> Seems like it's still here.

![screen shot 2018-04-26 at 16 33 31](https://user-images.githubusercontent.com/34530026/39298169-ac18dc84-496f-11e8-9d2e-a23aa63b28eb.png)
![screen shot 2018-04-26 at 16 33 39](https://user-images.githubusercontent.com/34530026/39298170-acc76060-496f-11e8-8b83-ceeb22fe8147.png)

**Comment by drepram** [comment]
It might not be common, but it is a bug.

**Comment by drepram** [comment]
Browser : Google Chrome - 68.0.3406.0 (Official Build) canary (64-bit)

Extensions : 

- DuckDuckGo Privacy Essentials
- GhostText
- Go Fucking Work
- Google Docs Offline
- JSON Viewer
- Lucid
- Notifier for GitHub
- Refined GitHub
- Refined Twitter
- Refined Wikipedia
- The Great Suspender
- Vue.js devtools
- Wappalyzer
- Web Maker

**Comment by filipekiss** [comment]
Can you please try disabling your extensions and enabling only Refined Twitter and see if that still happens?

**Comment by drepram** [comment]
I'm going to need some time to reproduce the bug, don't close this issue in the mean time.

**Comment by filipekiss** [comment]
No problem, we'll wait! It's just that I wasn't able to reproduce using my extensions, so maybe something is conflicting. I'll investigate it anyway while you do that! Thank you @caxvis.

**Comment by drepram** [comment]
I've disabled all of my extensions except for **Refined Twitter**, all the twitter pages we're loaded pretty fast. The bug never occurred.

It probably has some conflict with DuckDuckGo or one of my extensions, because when I enable all of my extensions again, the twitter pages we're being loaded pretty slow.

So no, this is not an issue with **Refined Twitter**, it is an issue with one of my extensions. This issue will now be closed.
