### ISSUE TITLE
Code block ruins link

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#108]
See this tweet: https://twitter.com/sindresorhus/status/994307954030526464

The `https://github.com/sindresorhus/sindresorhus` URL is a link when Refined Twitter is turned off. When it's on, it's just text. For some reason it's also showing the URL to the image as text `pic.twitter.com/xZdQSzFLAq`.

// @jorgegonzalez

**Comment by filipekiss** [comment]
Looking into it

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
