### ISSUE TITLE
Auto-loading new tweets in stream is not working

### ISSUE THREAD

**Issue by martellaj** [sindresorhus/refined-twitter#11]
One of the highlights in the README is "Auto-loads new tweets in the stream if you're scrolled to the top. No more clicking "See 3 new Tweets"!", but it doesn't seem like that feature actually works. I'm currently in that state and could provide a screenshot - but don't think that'd be very helpful. Please let me know what additional info you need to debug further.

**Comment by sindresorhus** [comment]
Are you scrolled all the way to the top?

**Comment by martellaj** [comment]
Yes.

* Windows
* Chrome
* Window is as wide as the feed and snapped

**Comment by sindresorhus** [comment]
I've pushed out a new release which should be out within an hour that should fix the problem.

**Comment by martellaj** [comment]
Awesome. What version should I look out for?

**Comment by sindresorhus** [comment]
`17.12.7.2200` (Versions are date-based)

**Comment by martellaj** [comment]
Where can I find the version number of what I have installed? Chrome is showing me a semver version.

![image](https://user-images.githubusercontent.com/1019478/33743051-02d3136a-db60-11e7-9fe0-74ca65005076.png)

**Comment by scttcper** [comment]
Mine pulled it in and fixed it. Its on the [chrome://extensions/](chrome://extensions/) page
![screen shot 2017-12-07 at 3 07 25 pm](https://user-images.githubusercontent.com/1400464/33743138-67bffcb6-db60-11e7-8685-b6f4d0a3d1f4.png)
you might have to check developer mode to find the update button at the top of the page

**Comment by martellaj** [comment]
Awesome. Yep, I was waiting on Chrome to update it. Didn't think to force the update. Have the correct version now - just waiting for a new tweet to roll in so I confirm the scenario. Thanks, @scttcper!

**Comment by martellaj** [comment]
Confirmed. Thanks, @sindresorhus!
