### ISSUE TITLE
Reduce height of header image

### ISSUE THREAD

**Issue by badboy** [sindresorhus/refined-twitter#11]
Right now the header image on profile pages takes up a large part of the site, hiding most of the tweets under the fold (just one, maybe 2 tweets are visible).

I'd like to have a content-first approach, reducing the height of the header image.

Current: ![](https://tmp.fnordig.de/scr/6c06718fd3.png)

Better: ![](https://tmp.fnordig.de/scr/876f395205.png)

**Comment by sindresorhus** [comment]
👍 Maybe reduce the width too so it doesn't get that much cropped. Wanna try doing a pull request?
