### ISSUE TITLE
Remove cards from links from code blocks

### ISSUE THREAD

**Issue by filipekiss** [sindresorhus/refined-twitter#110]
The links rendered from code blocks should be detected and removed from tweet cards. 

Basically turn this:
![image](https://user-images.githubusercontent.com/48519/39877563-a1c49632-544c-11e8-9e55-c599887f0d8d.png)

Into this:
![image](https://user-images.githubusercontent.com/48519/39877597-b567551c-544c-11e8-8a8f-ebdc84d0118b.png)

**Comment by jorgegonzalez** [comment]
I'll try picking this up soon.

**Comment by jorgegonzalez** [comment]
It might be an edge case, but do we also want to keep link cards in situations when there are links in a tweet that also happens to have a code block?

![image](https://user-images.githubusercontent.com/12901172/40074586-f6f3351a-5847-11e8-915b-8c50a682244f.png)

**Comment by filipekiss** [comment]
Yeah, that's actually the main concern. My idea was to detect links that come from inside the code blocks and remove the related cards. If there are links outside the code block, keep'em.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
