### ISSUE TITLE
Going to settings toggles night mode, menu floats to the left

### ISSUE THREAD

**Issue by hmemcpy** [sindresorhus/refined-twitter#111]
Chrome 66.0.3359.139 (Official Build) (64-bit)
Refined Twitter 18.4.29.937

Looks like this:
![image](https://user-images.githubusercontent.com/601206/39887018-c3502a6c-5499-11e8-9c4f-9e8d9f2b1cba.png)

if browser window is made smaller, the menu floats on top of the content.

**Comment by hmemcpy** [comment]
Looks like going into the settings again, after it switched to night mode, will toggle it off.

**Comment by filipekiss** [comment]
This is due to centering the timeline (and maybe removing the header).

We shouldn't mess with the settings options, probably.
