### ISSUE TITLE
Set up Travis again

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/refined-twitter#114]
GitHub made a change to how the CI works and it needs to be set up again, at least I think so, as the CI checks aren't running in the two most recent PRs. https://blog.github.com/2018-05-07-introducing-checks-api/

**Comment by sindresorhus** [comment]
Weird, I tried to enable it again now.

**Comment by sindresorhus** [comment]
> Open source projects on Travis CI will soon have the option to migrate over to travis-ci.com. We’ll do a wider announcement when this is ready. Read more about this in our docs.
