### ISSUE TITLE
Explore basic support for mobile.twitter.com

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/refined-twitter#115]
The Twitter Mobile site was rewritten in React sometime after the original Refined Twitter extension was deprecated, and it currently outperforms the desktop app significantly (and unrelated, but I suspect the desktop app will also be updated soon).

Hiding the sidebar, centering the feed, and adding a Likes button to the navbar are some basic tweaks we can make initially.

One potential issue may be that CSS classnames are being obfuscated due to their use of CSS Modules or something: 

![image](https://user-images.githubusercontent.com/12901172/40445701-e21c1824-5e9a-11e8-9610-8a29ffbea1a1.png)

**Comment by filipekiss** [comment]
Sindre had a project that targeted mobile twitter and he stopped maintaining it exactly because of CSS obfuscation: https://github.com/sindresorhus/anatine

I don't see a way to work around that just yet =(

**Comment by jorgegonzalez** [comment]
Wow I had no idea that was why it was deprecated.

If the desktop app gets rewritten then this project would be in trouble too.

**Comment by filipekiss** [comment]
Yeah. CSS Modules is great for a lot of reasons, but it breaks things like this =/
