### ISSUE TITLE
The "Likes" button is sometimes placed incorrectly

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#116]
When I load twitter.com fresh, the Likes button is sometimes placed in the wrong location:

<img width="926" alt="screen shot 2018-05-24 at 16 41 06" src="https://user-images.githubusercontent.com/170270/40477950-f8f083e6-5f71-11e8-82a2-5e0b9bab5bd2.png">

**Comment by jorgegonzalez** [comment]
I’ve noticed this too.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
