### ISSUE TITLE
Release an own Firefox add-on

### ISSUE THREAD

**Issue by jezdez** [sindresorhus/refined-twitter#118]
While I admit the [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) is a nifty way to handle the differences in packaging of Web Extensions between Chrome and Firefox, it also asks for a *lot* of permissions: 
<img width="374" alt="screen-shot-2018-06-06-18-17-34" src="https://user-images.githubusercontent.com/1610/41051288-f7261596-69b5-11e8-9d8e-d40bf49a2799.png">

I would politely suggest to follow the setup of https://github.com/sindresorhus/refined-github, which probably means fixing #114 right? If I were to send a PR to do that, would you accept it?

**Comment by salmanulfarzy** [comment]
It was discussed at #20 and maintainers were clear about not supporting Firefox directly because of the reasons discussed there and https://github.com/sindresorhus/merge-windows/issues/4#issuecomment-336848043 :disappointed:

**Comment by jorgegonzalez** [comment]
I think the main issue was that @sindresorhus didn't want to publish it on AMO with the same name.

**Comment by sindresorhus** [comment]
Anyone is free to publish it to AMO under a different name. I do this project for fun and AMO is not fun.

**Comment by jezdez** [comment]
@salmanulfarzy Ah, thank you for the link, I must have missed it when I looked earlier.

@sindresorhus Okay, that wasn't really the question, but I see that you're frustrated by AMO so I won't try to ask you to change your mind about it. No offense intended.

Since forking the project to publish it under a different name would increase the maintenance burden unreasonable IMO (e.g. syncing code updates, implement fixes for AMO reviews etc), would you be willing to add me as a collaborator and let me handle the release on AMO?

**Comment by timmyRS** [comment]
@sindresorhus I'm maintaining a Chrome Extension of my own for which I do all the developing and testing in Chrome and for each new release I just zip it and upload it to the Chrome Webstore & AMO and I've never had any problem with it, nor is it any hard work. You're just uploading 1 zip file to 2 websites. God forbid you to have to upload a file and press 2 buttons!!!

Seriously, stop being lazy, dude.

**Comment by sindresorhus** [comment]
@timmyrs I’m gonna leave your reply here as it’s more embassaring for you than it hurts me.

**Comment by sindresorhus** [comment]
@jezdez Alright. Let’s do it. Seeing how popular this project is, I will put my personal feelings aside for the health of the project. You can follow how Firefox support is done in Refined GitHub.

**Comment by jezdez** [comment]
@sindresorhus Thank you, I really appreciate it!

**Comment by ThibaultVlacich** [comment]
Considering that Chrome Store Foxified doesn't work anymore on the latest version of Firefox, that would be great! 👍

**Comment by MasterOfTheTiger** [comment]
I have a fork for AMO.

**Comment by filipekiss** [comment]
@jezdez I've switched to FF as my main browser. Let me know if you need any help!

**Comment by jorgegonzalez** [comment]
Any update on this?

**Comment by akilangh** [comment]
Let me know what kind of help is needed to make this into Firefox. I'm willing to help.

**Comment by salmanulfarzy** [comment]
Foxified has been [discontinued][1] for now.

[1]: https://github.com/Noitidart/Chrome-Store-Foxified/issues/122

**Comment by MasterOfTheTiger** [comment]
Currently there is an add-on called Reimagined Twitter in AMO which is a fork of this. I have been maintaining it so that @sindresorhus doesn't have to deal with it.

**Comment by divyanshu013** [comment]
Thanks @MasterOfTheTiger, I think this issue may be closed, your extension is working fine 👍

**Comment by salmanulfarzy** [comment]
I think this issue is still valid and @MasterOfTheTiger has done great job with that fork. But issues with forking project still exists,

> Since forking the project to publish it under a different name would increase the maintenance burden unreasonable IMO (e.g. syncing code updates, implement fixes for AMO reviews etc), 

https://github.com/sindresorhus/refined-twitter/issues/118#issuecomment-395159347

If I remember correctly reimagined-twitter diverged considerably from refined-twitter previously.

**Comment by MasterOfTheTiger** [comment]
@salmanulfarzy You are right about me not keeping up to date with Refined Twitter in the past. Recently I redid my form from Refined Twitter to fix merging issues.

The only thing that is different in my fork is the name, and it works quite well. You guys are giving me too much credit. :P You guys here did all the hard work of making the extension work so well, and I respect @sindresorhus's decision not to manage it in AMO. 

If something does come up as a problem in Firefox, I will be sure to fix it, but nothing appears to be amiss right now.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
