### ISSUE TITLE
Breakes some social share plugins 

### ISSUE THREAD

**Issue by guneysus** [sindresorhus/refined-twitter#12]
Clicking twitter share button in this page, redirects "Page does not exists" page.
https://blogs.msdn.microsoft.com/yizhang/2010/12/17/interpreting-hresults-returned-from-netclr-0x8013xxxx/

![refined-twitter](https://cloud.githubusercontent.com/assets/949232/15039586/eb4d3bee-12b6-11e6-96d3-a5c4854c649d.PNG)

**Comment by sindresorhus** [comment]
Thanks for reporting this. Fixed in 0.2.2 :)
