### ISSUE TITLE
Profile sites layout issues

### ISSUE THREAD

**Issue by jahirfiquitiva** [sindresorhus/refined-twitter#121]
Hello

I love this extension and its features. Unfortunately, I am facing an issue that I find slightly annoying.

As you can see in the picture, the profile photo and counters (likes, tweets, followers, following) along with the "Follow" button, are behind the nav at the top.

It _sometimes_ gets fixed with a reload. Also, the issue doesn't always happen. Just randomly

I have tested this in a MacBook Air 2017 using Google Chrome

![screenshot at jun 13 22-43-39](https://user-images.githubusercontent.com/10360816/41391563-0b2e74e2-6f61-11e8-9e9d-ccc0d002fd12.png)

**Comment by jorgegonzalez** [comment]
I've noticed this as well. A refresh will usually fix it for me. I'm guessing this is being caused by some CSS loading too early.

Possibly related #102

**Comment by vinkla** [comment]
I'm also seeing this issue on profile pages.

<img width="953" alt="screenshot 2018-08-14 at 19 31 07" src="https://user-images.githubusercontent.com/499192/44107723-9ffee030-9ff8-11e8-98ac-d4cca88876cc.png">

**Comment by keysmashes** [comment]
If the viewport is less than 900px tall, the header displays normally on profile pages:

![image](https://user-images.githubusercontent.com/9433472/44300312-c11a8880-a2fc-11e8-83fd-16ce6e020976.png)

but any taller than that and it breaks:

![image](https://user-images.githubusercontent.com/9433472/44300316-cc6db400-a2fc-11e8-95dc-9425bb73644b.png)

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
