### ISSUE TITLE
Inline code blocks not applied correctly

### ISSUE THREAD

**Issue by loilo** [sindresorhus/refined-twitter#123]
See this tweet: https://twitter.com/MartijnSaly/status/1011223724496957441

![image](https://user-images.githubusercontent.com/1922624/41854036-81d4a4e0-788f-11e8-8729-3eac9d078626.png)

Couldn't find the reason in the extension's source code, fiddling with it in the dev tools does everything as expected...

**Comment by jorgegonzalez** [comment]
This will be fixed in #113

**Comment by loilo** [comment]
Looks nice. Thanks for taking care! 🎉

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
