### ISSUE TITLE
Make plugin work when user is not logged in

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [sindresorhus/refined-twitter#126]
doesnt seem to work, does it work as of this post? do you need to be login for it to work?

**Comment by jorgegonzalez** [comment]
You do need to be logged in.

**Comment by SolveAllProblemsRightNow** [comment]
... please add the basic info to both 

- https://chrome.google.com/webstore/detail/refined-twitter/nlfgmdembofgodcemomfeimamihoknip

- and https://github.com/sindresorhus/refined-twitter

since right click icon > refined goes to the github page, not chrome page

**many of us dont use twitter with an account, if possible please make it work without a login**

**Comment by jorgegonzalez** [comment]
Most features assume that a user is logged in, and I don’t think this is a common use case.

**Comment by filipekiss** [comment]
@SolveAllProblemsRightNow What exactly you want to work without logging in? Most of the modifications are related to how the timeline behaves and that only exists when the user is logged.

**Comment by sindresorhus** [comment]
We're not going to support logged-out mode as none of us use that, but we can make it clearer that it only works logged-in, sure.

**Comment by SolveAllProblemsRightNow** [comment]
>Most of the modifications are related to how the timeline behaves and that only exists when the user is logged.

well there we go, no need then

i rarely use twitter also

---

to make clearer, should put on those two pages linked before

especially the chrome description page since that's where 99.9% of users will see first
