### ISSUE TITLE
Top bar totally broken in non-English language

### ISSUE THREAD

**Issue by piotrkulpinski** [sindresorhus/refined-twitter#129]
Hi, 

The layout of the top bar is broken when language is set to a different language then English (Polish in this case).

https://www.dropbox.com/s/2skmo03kua4zuoy/Screenshot%202018-08-01%2012.15.05.png?dl=0

This is probably caused by longer labels in this language but I believe this could also be an issue with others.

Thanks, Piotrek

**Comment by OleksandrBilenko** [comment]
Hi! I found the way to fix it. Go to extension settings and turn off 'Hide the header image on profile pages' option.

1. Open chrome://extensions/  
2. Click Refined Twitter (Details button)
3. Click Extension options
4. Uncheck 'Hide the header image on profile pages'

There are also many useful checkboxes, try it :)

**Comment by hmemcpy** [comment]
@OleksandrBilenko oh my! I didn't know these were exposed as options! Thanks so much!
This also solves another personal annoyance (I like to know who followed me.)
Thanks again, I can live with the header image not being hidden!

![image](https://user-images.githubusercontent.com/601206/44475580-15e03b00-a63e-11e8-8e8d-b52cf194d6f6.png)

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
