### ISSUE TITLE
add setting to hide media by default. 

### ISSUE THREAD

**Issue by tomnewton** [sindresorhus/refined-twitter#13]
would make it much cleaner.

**Comment by paulmolluzzo** [comment]
Not a fan of this personally, I'd prefer to just scroll and browse.

**Comment by sindresorhus** [comment]
It might be cleaner, but these days the media is an important part of the tweet and without many tweets would be incomprehensible until you clicked it. Could easily be done as a separate extension if anyone really wants this though ;)
