### ISSUE TITLE
Investigate and eliminate lag with default Twitter site

### ISSUE THREAD

**Issue by kurisubrooks** [sindresorhus/refined-twitter#13]
Hope this is worth looking into;
I experience pretty intense lag on both my desktop (powerful gaming pc) and my laptop (macbook air) after having the site open for a couple of minutes (with & without this extension installed) it slowly becomes unusable due to the sheer amount of lag between actions, specifically scrolling, liking tweets, videos lagging, etc. Taking a look into Chrome's Task Manager i've found, whilst having multiple tabs open, Twitter has both the highest CPU usage and most memory usage of all of my tabs open. 

I'd greatly appreciate if this could be looked into, as it would certainly make the site alot more usable to people who experience the same issue as I. Thanks a bunch!

![screenshot 2017-12-08 10 58 22](https://user-images.githubusercontent.com/6291467/33744832-526b008e-dc07-11e7-9755-6a68fe4b3f3b.png)

**Comment by sindresorhus** [comment]
For anyone wanting to look into this, try using the "Performance" tab in Dev Tools.

**Comment by obahareth** [comment]
Here are a couple of screenshots from the performance tab:

<img width="947" alt="screen shot 2019-02-13 at 4 52 25 pm" src="https://user-images.githubusercontent.com/3428118/52716570-15eb4300-2fb0-11e9-81dc-04e85e63bfe4.png">
<img width="296" alt="screen shot 2019-02-13 at 4 52 33 pm" src="https://user-images.githubusercontent.com/3428118/52716576-197eca00-2fb0-11e9-8411-7684f2fc7831.png">
<img width="947" alt="screen shot 2019-02-13 at 4 53 59 pm" src="https://user-images.githubusercontent.com/3428118/52716580-1b488d80-2fb0-11e9-8ea6-b83880833c99.png">


The `content.js` in the last image is from `refined-twitter`.

This is the minified code of the first one:

```js
const f = (new (n.n(l).a)).getAll()
      , d = async({fn: e, id: t=e.name})=>{
        u || (u = await f);
        const {logging: n=!1} = u
          , r = n ? console.log : ()=>{}
          , a = t.replace(/_/g, "-");
        if (/^$|^anonymous$/.test(a))
            console.warn("This feature is nameless", e);
        else if (!1 === u[a])
            return $("html").removeClass(a),
            void r("↩️", "Skipping", a);
        try {
            $("html").addClass(a),
            await e(),
            r("✅", a)
        } catch (e) {
            console.log("❌", a),
            console.error(e)
        }
    }
```

And this is the second one:


```js
()=>{
  Object(i.b)(o.b.codeHighlight),
  Object(i.b)(o.b.mentionHighlight),
  Object(i.b)(o.b.inlineInstagramPhotos),
  Object(i.b)(o.b.renderInlineCode),
  Object(i.b)(o.b.imageAlternatives),
  Object(i.b)(o.b.hideRetweetButtons)
}
```

I haven't looked deeply enough to see why these are slow, but I thought I'd at least log my findings here. These were the top two function calls in terms of total execution time.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
