### ISSUE TITLE
Vertical gap in settings views

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-twitter#130]
There is this large vertical gap between first form field and other fields in the settings view. This doesn't happen when I disable the extension.

![image](https://user-images.githubusercontent.com/37769974/43677941-0a9401b0-9828-11e8-9c44-b6cb94c407fa.png)

![image](https://user-images.githubusercontent.com/37769974/43677945-21184c48-9828-11e8-9d2e-c9ca772f392f.png)

**Comment by jorgegonzalez** [comment]
The whole settings page needs to be patched up. #111 is related.

Would you like to try fixing this @notlmn?
