### ISSUE TITLE
Show twitter explore tab

### ISSUE THREAD

**Issue by sidahmed-malaoui** [sindresorhus/refined-twitter#136]
Can you add the twitter explore tab like it is show in the twitter phone application.

**Comment by sindresorhus** [comment]
What is the Explore tab? Can you share a screenshot?

**Comment by sidahmed-malaoui** [comment]
This is the explore tab, it is only available in twitter app for android or IOS, and also available from the site [mobile.twitter.com](mobile.twitter.com) . 

In this tab we can see trends, also some topics that are interesting for us.
![twitter](https://user-images.githubusercontent.com/19175347/44341189-18486680-a47f-11e8-9247-dca7f4f0d902.png)
