### ISSUE TITLE
I can't disable 「Hide "Profile" Card」from extension menu checkbox

### ISSUE THREAD

**Issue by ryota-murakami** [sindresorhus/refined-twitter#138]
## About
I've been turn off「Hide "Profile" Card」feature on menu, but still Profile Card image hiding.

I'd like to know is this error occurring on only me?
If anyone have a same issue, I'm glad to know through comment😀

## Movie
https://www.dropbox.com/s/lle2xubbwmt4uso/hide-profile-unable.mp4?dl=0

**Comment by sindresorhus** [comment]
// @brunolemos

**Comment by ryota-murakami** [comment]
I'm afraid, I misunderstood.
I expected `Hide the header image on profile pages`'s function to `Hide "Profile" Card`.

Currently the extension has no problem.
It's my fault🙇‍♂️

**Comment by brunolemos** [comment]
The `Hide Profile Card` refers to the Home screen, not the Profile screen:

<img height="80" src="https://user-images.githubusercontent.com/619186/44948677-5b4bf780-adf8-11e8-848a-1c3aa3cbad43.png" />


<img height="350" src="https://user-images.githubusercontent.com/619186/44948611-20958f80-adf7-11e8-8ac8-5f1d2851a4ec.png" />
