### ISSUE TITLE
Hide retweet button

### ISSUE THREAD

**Issue by ianstormtaylor** [sindresorhus/refined-twitter#147]
There's an [article on the Atlantic](https://www.theatlantic.com/magazine/archive/2018/04/the-case-against-retweets/554078/) that makes a case for hiding all retweets in your feed.

> A couple of months ago, I made a small tweak to my Twitter account that has changed my experience of the platform. It’s calmer. It’s slower. It’s less repetitive, and a little less filled with outrage. All of these improvements came about because I no longer see retweets.

It might be a bit drastic to be enabled by default (although maybe not), but it would be really nice is this were available as an option so that folks could experiment with it easily and see if it's for them. 

I've just personally scrolled through my feed and checked, and almost every retweet was something I wouldn't miss at all. Most were self-promotion (usually because the person doesn't really realize how often they are retweeting useless stuff, myself included).

Related: it would be also a cool option to be able to hide the retweet button entirely, to prevent yourself from adding to the retweet noise. (I'm definitely guilty of this.)

Thank you!

**Comment by sindresorhus** [comment]
The ability to hide retweets was added in https://github.com/sindresorhus/refined-twitter/pull/142.

**Comment by sindresorhus** [comment]
> Related: it would be also a cool option to be able to hide the retweet button entirely, to prevent yourself from adding to the retweet noise. (I'm definitely guilty of this.)

👍 PR welcome. Should be opt-in.

**Comment by ianstormtaylor** [comment]
@sindresorhus ah oops, I was using an older version. Thank you! That is awesome!
