### ISSUE TITLE
Add Bookmarks from mobile to desktop functionality

### ISSUE THREAD

**Issue by sgraymackenzie** [sindresorhus/refined-twitter#153]
Is it possible to pull the bookmark feature from mobile (https://mobile.twitter.com/i/bookmarks) and add it as an option to the desktop version via this extension?

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
