### ISSUE TITLE
HUGE Performance conflict with Adblock Plus

### ISSUE THREAD

**Issue by ZacWolf** [sindresorhus/refined-twitter#155]
I'm seeing a HUGE performance hit when using Refined Twitter and Adblock Plus at the same time. This one makes perfect sense since the two, depending on your Refined Twitter setting, are competing to do the same job. 

Disabling Adblock Plus for twitter.com did the trick. This info might need to be added to the readme.md or any FAQ?

Thanks!

**Comment by jorgegonzalez** [comment]
I would suggest switching to uBlock Origin, which is an overall better content blocker, and has no noticeable performance conflict with Refined Twitter.

**Comment by jorgegonzalez** [comment]
But to address your issue, I suspect Adblock Plus is at fault here (as they are known for poor performance).

**Comment by ZacWolf** [comment]
Yeah, like I said, I just disabled Adblock Plus for twitter.com and everything was good.
Just mentioning it to maybe add that to readme/faq as users of Adblock Plus that install Refined Twitter are probably going to quickly uninstall given how bad the performance becomes.

**Comment by jorgegonzalez** [comment]
Sure, feel free to send a PR.
