### ISSUE TITLE
Hide like button

### ISSUE THREAD

**Issue by ianstormtaylor** [sindresorhus/refined-twitter#156]
It would be nice to be have the option to hide the "Like" heart button with the likes count, since clicking it sometimes results in "this person liked" popping up in other peoples's feeds. And it removes some of the social gaming of counting likes as well since you can't see the numbers anymore.

Just an idea!

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
