### ISSUE TITLE
Option to hide "liked your tweet"/"retweeted your tweet" from Notifications

### ISSUE THREAD

**Issue by ahmetb** [sindresorhus/refined-twitter#157]
I see there's already these settings for **Notifications** tab:
![image](https://user-images.githubusercontent.com/159209/49242935-e8cfc100-f3c0-11e8-86b3-8ed80f7d1ae8.png)

But I actually find "likes" and "retweets" on my tweets redundant. Maybe there should be

a. have an option likes/tweets (just like the options above)
b. have an option to remember which tab was visited on Notifications (among "All" vs "Mentions"), so if I click "Mentions" once, I'll land there forever.

I know these have some repercussions like if you have likes/RTs on your tweets, the badge indicator on the top will still light on etc but you won't be able to see them (annoying).

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
