### ISSUE TITLE
Auto Deploy to Chrome

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-twitter#16]
@sindresorhus do you want to set up the auto-deploy process again via Travis CI? I can do the setup in the .travis.yml and what not if you can go grab the necessary API keys to add as env vars.

This still needs to be packaged or made into an app...

**Comment by sindresorhus** [comment]
👍 Sure :)

**Comment by paulmolluzzo** [comment]
Closed with #35
