### ISSUE TITLE
Download images in original size

### ISSUE THREAD

**Issue by piotrmil** [sindresorhus/refined-twitter#162]
Only today learned that if you add ":orig" at the end of the image's url, it shows its original size. It would be cool if one could use that upon downloading an image via right click. This is kinda important since nowadays twitter is filled with lots of artists from tumblr, after they killed raw images like four months ago or something.

**Comment by sindresorhus** [comment]
We already do that: https://github.com/sindresorhus/refined-twitter/blob/ad99eb418f9a72fae9077c4d551faa66f3034e8d/source/background.js#L33 Not on right-click, as that would be impossible, but on load.
