### ISSUE TITLE
Option for "real" chronological tweet layout (old -> new)

### ISSUE THREAD

**Issue by chuckthenerd** [sindresorhus/refined-twitter#163]
The typical timeline is reverse chronological with the most recent entries at the top... 
e.g. the tweet "and they lived happily ever after" would be at the top and "Once upon a time" would be listed lower, along with an option to "load earlier tweets" at the very bottom.

I'd love to have a Refined Twitter option where the top of the screen has "load earlier tweets" followed by "Once upon a time" then followed by the story which then ends with "and they lived happily ever after". and maybe "load newer tweets" at the bottom.  In essence have twitter read like a book/scroll.

**Comment by jorgegonzalez** [comment]
We appreciate the suggestion, but this would be incredibly difficult to implement, so I'm closing this issue for now.
