### ISSUE TITLE
Likes tab is some times placed in the home tab position

### ISSUE THREAD

**Issue by jahirfiquitiva** [sindresorhus/refined-twitter#164]
Hello

I love this extension but for some reason, some times the "Likes" tab is placed where the "Home" tab should be and it's super annoying because one unconsciously already assumes/remembers the "Home" tab is the first item so one ends up clicking the wrong tab.

Can you please look into it and provide a fix soon? Thanks in advance!

**Expected behavior:**
![captura de pantalla 2019-02-04 a la s 7 39 36 p m](https://user-images.githubusercontent.com/10360816/52246684-a93bbe80-28b4-11e9-987d-f40de1f5a197.png)

**Actual behavior (which happens randomly):**
![captura de pantalla 2019-02-04 a la s 7 34 14 p m](https://user-images.githubusercontent.com/10360816/52246643-7abde380-28b4-11e9-9f65-05460090c0d6.png)

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
