### ISSUE TITLE
Extension not working with the new version of Twitter

### ISSUE THREAD

**Issue by iRaul** [sindresorhus/refined-twitter#165]
Hey there 👋

First, great job! I really love this extension ❤️

I recently updated to the new twitter and apparently the extension isn't working 🙁

Thanks!

**Comment by julianshapiro** [comment]
Can confirm.

**Comment by jorgegonzalez** [comment]
https://github.com/sindresorhus/refined-twitter/issues/141 Related

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
