### ISSUE TITLE
Img optimizations for the feed

### ISSUE THREAD

**Issue by kurtextrem** [sindresorhus/refined-twitter#166]
Use `decoding=async` on images, `intrinsicsize="YxY"`, maybe `lazyload` and `importance=low/high`. Those all could speed up the feed.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
