### ISSUE TITLE
Fix or drop blinking floating labels

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-twitter#167]
I can't believe this has been _the norm_ on Twitter for years. It's still broken.

![d](https://user-images.githubusercontent.com/1402241/53430023-aa31bd00-3a28-11e9-86c0-d717f52a2e6c.gif)

It's so easily-reproducible it makes me wonder if anyone at Twitter cares about anything.

**Comment by sindresorhus** [comment]
> if anyone at Twitter cares about anything

I don't think they ever did. At least that's my experience.

**Comment by sindresorhus** [comment]
I don't see the point of those tooltips regardless. Let's drop them.

**Comment by jorgegonzalez** [comment]
Not saying we shouldn't drop them, but isn't the point accessibility?
