### ISSUE TITLE
Empty space in a list timeline

### ISSUE THREAD

**Issue by juandarr** [sindresorhus/refined-twitter#169]
Browser: Firefox 66.0b11 with extension Foxified.
OS: Windows 10

I am getting the following empty space when clicking on any of my twitter personal lists:

![screenshot 476](https://user-images.githubusercontent.com/749275/53625375-e9027700-3bd0-11e9-86ae-4a789015830c.png)
Does anyone know how to fix it? I checked the item with the Firefox inspector and the element has the class "stream-item js-new-items-bar-container" linked.
This problem is not present when using the Chrome browser.

**Comment by juandarr** [comment]
After doing some research I found that enabling the option **Hide "Who to follow" Card** results in this bug when opening lists in Firefox. This option also disables the **recently added members'** box from the list view in the right-hand side.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
