### ISSUE TITLE
Improve styling of profile avatar alt texts

### ISSUE THREAD

**Issue by loilo** [sindresorhus/refined-twitter#171]
I love the alt text feature, but what regularly bothers me is the slightly distorted (oval) display of user avatars:

![User avatar distorted through display of alt text](https://user-images.githubusercontent.com/1922624/54077348-4a080a00-42b7-11e9-912d-8429c499b4fa.png)

I think it would look a lot nicer to style avatar alt text something like this:

![Non-distorted user avatar with alt text below the picture](https://user-images.githubusercontent.com/1922624/54077358-70c64080-42b7-11e9-82ef-2c365386e981.png)

Thoughts on this?
I'd be happy to attach a PR.

**Comment by jorgegonzalez** [comment]
We'd be happy to merge a PR fixing this.
