### ISSUE TITLE
Having trouble getting Refined Twitter to work (Console Debug screenshot included)

### ISSUE THREAD

**Issue by sm01-uk** [sindresorhus/refined-twitter#174]
I can't seem to get Refined Twitter to work with Twitter. I am using it on a Chromebook, with up to date version of ChromeOS. Included a screenshot including the Console info which suggests a problem of some sort.
![Screenshot 2019-03-21 at 10 27 57](https://user-images.githubusercontent.com/48791441/54746738-d6260580-4bc4-11e9-97d3-01d2868ea8dd.png)

**Comment by jorgegonzalez** [comment]
That appears to be the redesign or Twitter for mobile, neither of which we currently support.

**Comment by sm01-uk** [comment]
Thanks very much for your reply - I'm not actually using the
mobile.twitter.com just twitter.com itself - does that still stand, and is
there anything I might be able to do to work around it? Does this mean that
Refined Twitter just doesn't work with the newer version of Twitter?

Thanks again.

**Comment by jorgegonzalez** [comment]
Yes, unfortunately Refined Twitter doesn’t work on the new version of Twitter. No workarounds currently.

**Comment by sm01-uk** [comment]
That's a pity, it seems like such a useful tool. Thanks for your reply in
any case.
