### ISSUE TITLE
Instagram placeholder is shown when URL links to no image

### ISSUE THREAD

**Issue by bardware** [sindresorhus/refined-twitter#177]
In this case the instagram link points to a tag, not to a single image. The placeholder image is still shown

![image](https://user-images.githubusercontent.com/802702/55117280-8aa2b880-50ea-11e9-83b6-09956f6f307c.png)

**Comment by sindresorhus** [comment]
Can you share the link to the tweet so we can test?

**Comment by sindresorhus** [comment]
// @filipekiss

**Comment by bardware** [comment]
This tweet: https://twitter.com/jamiattenberg/status/1110977343294705664

**Comment by filipekiss** [comment]
I'll take a look. It's weird because it should only try to load photo tags. I tested with profile links but since I've never even seen a link to tags in the wild before, it didn't cross my mind! Thanks @bardware

**Comment by bardware** [comment]
Seen it working, thanks again! :)
