### ISSUE TITLE
Option to remove follower/following count/all number counts on profile

### ISSUE THREAD

**Issue by jl98** [sindresorhus/refined-twitter#179]
I really love this extension, and I think it would be really great if you could hide the number counts on your own profile. I personally do not care about how many followers/how many folks I'm following, so getting rid of numbers would be a nice way to simply the Twitter experience.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
