### ISSUE TITLE
prevents uploading a profile picture

### ISSUE THREAD

**Issue by aspiers** [sindresorhus/refined-twitter#181]
I just set up a new account and wanted to add a profile picture, but after clicking on the blank profile pic to add one, absolutely nothing happened.  After a few minutes of useless fumbling around, I gave up and uploaded one from my Android phone's Twitter app.  Then it occurred to me that a Twitter extension might be at fault.  After disabling this extension, suddenly I found that the "Change your profile photo" button now works, and re-enabling the extension breaks it again.  I presume this would be the same if I hadn't already uploaded one from Android and the button still said "Add a profile photo".

FWIW, I have one other Twitter-oriented extension installed: [Twitcher](https://chrome.google.com/webstore/detail/twitcher-twitter-account/gmngpagflejjoblmmamaonmnkghjmebh).

**Comment by jorgegonzalez** [comment]
I can reproduce.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
