### ISSUE TITLE
Options showing nothing in Chrome 73

### ISSUE THREAD

**Issue by stefanjudis** [sindresorhus/refined-twitter#182]
Heyo, thanks so much for this great extension. 

I just wanted to give #179 a spin but unfortunately, the options dialog is not loading properly for me running in developer mode following the contribution instructions. I tried it in Canary and also incognito mode. It looks like follows. 👇

<img width="571" alt="Screenshot 2019-04-23 at 21 54 04" src="https://user-images.githubusercontent.com/962099/56611616-7af79080-6612-11e9-99aa-1be6fb10b36c.png">

Thanks a bunch. :)

**Comment by jorgegonzalez** [comment]
Sorry for the delayed response. Not sure if this is still an issue for you, please re-open this if it is. Closing as I can't reproduce.
