### ISSUE TITLE
New Twitter layout: "Trends for you" and "Who to follow" started showing up again.

### ISSUE THREAD

**Issue by Tushkiz** [sindresorhus/refined-twitter#183]
This may be due to the new twitter layout. How can I contribute, I love this extension.

**Comment by Dragonissa** [comment]
Yep, doesnt seem to work for me at all and i hate the new mobile ui for web >_>

**Comment by drkthng** [comment]
I'll second that!

**Comment by Tushkiz** [comment]
Inspect element shows that they are using some kind of CSS class minification, but there is a way to select the whole sidebar and hide both at once. Downside these features cannot be toggled individually
