### ISSUE TITLE
Replace Top Tweets with Latest Tweets

### ISSUE THREAD

**Issue by ardalis** [sindresorhus/refined-twitter#185]
Twitter prefers to show their top tweets. You can switch to latest tweets, but after a few days Twitter will switch you back to their preference. Can the extension keep the default behavior of latest tweets and automatically switch (back) to this whenever Twitter tries to switch (back) to top tweets?

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
