### ISSUE TITLE
Hiding 'Trends' in the new UI also hides the search bar 

### ISSUE THREAD

**Issue by hmemcpy** [sindresorhus/refined-twitter#187]
First of all, thank you for keeping this wonderful extension alive after the twitter redesign!

It seems that using the new `Hide "Trends for you" and "Who to follow" cards in the new Twitter UI` option unfortunately also removes the "Search Twitter" bar.

Would it be possible to leave it as is?

**Comment by piotrmil** [comment]
Yeah, that needs to be fixed asap.

He says a month  later when it's not fixed.

**Comment by jorgegonzalez** [comment]
Refined Twitter currently does not work on the redesign. Please add this comment to #141 so we can keep track of features that we would like to re-implement.
