### ISSUE TITLE
promoted tweets not hidden

### ISSUE THREAD

**Issue by emanut** [sindresorhus/refined-twitter#188]
I still can see promoted tweets and trends.

Chrome Version 75.0.3770.80 (Offizieller Build) (64-Bit)
MacOS 10.14.4 (18E226)

Thank you

**Comment by sindresorhus** [comment]
Are you on the new Twitter design? If so, almost none of the features are ported yet.

**Comment by emanut** [comment]
Thank you for the quick reply. Switched back to old layout.
