### ISSUE TITLE
Search function gone with 'What's Happening' and 'Who To Follow' boxes

### ISSUE THREAD

**Issue by voltwaffle** [sindresorhus/refined-twitter#197]
As shown in the image, the search function that should be at the top right side has disappeared. I couldn't find anything in the options menu to change it. Thank you in advance.

![refinedtwitter](https://user-images.githubusercontent.com/65451619/82120285-869c8480-974a-11ea-824e-20a7ed6ca755.JPG)

**Comment by yuanLeeMidori** [comment]
May I send PR to fix this issue? I've fixed this issue in my forked repo with taking back the search function in the `Hide "Trends for you" and "Who to follow" cards in the new Twitter UI` option.

Thank you!

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
