### ISSUE TITLE
Is Firefox still supported?

### ISSUE THREAD

**Issue by edouard-lopez** [sindresorhus/refined-twitter#199]
Hello @sindresorhus, 
thanks for yet another great project!

The repo still has a keyword `firefox-addon` and instructions to install on Firefox in the [contribute section](https://github.com/sindresorhus/refined-twitter#contribute).

But I also this PR #158 to remove Firefox instructions has been merged and nothing in the Mozilla store.

So what's a status?

**Comment by sindresorhus** [comment]
This extension is deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
