### ISSUE TITLE
Native Firefox support

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/refined-twitter#20]
For more streamlined experience

**Comment by sindresorhus** [comment]
How is it not streamlined, currently? Yes, you have to install an extension to be able to install Refined Twitter from the Chrome Web Store, but then you can also install any other Chrome extension without waiting for it to eventually (or most likely never) end up in AMO.

I also have personal reasons to not use AMO again: https://github.com/sindresorhus/merge-windows/issues/4

**Comment by YurySolovyov** [comment]
Ok, that's fair, feel free to close this one

**Comment by jorgegonzalez** [comment]
@sindresorhus Why don't you allow someone else to publish it on AMO, then?

**Comment by Hoishin** [comment]
The source code is here and it’s MIT a licensed...

**Comment by jorgegonzalez** [comment]
Well, I'd be happy to do so with the maintainers' blessing.

**Comment by filipekiss** [comment]
For me, as long as you give credit where credit is due and use a different name so people will know that the extension at AMO is not maitained in this repo, you are free to fork and release it. Maybe we can even link it on the README.

Let's see if @sindresorhus has anything against it.
