### ISSUE TITLE
Reduce image height in preview while composing tweets

### ISSUE THREAD

**Issue by ashander** [sindresorhus/refined-twitter#27]
image preview often pushes the button to add additional images out of the bottom of the window. there's no scroll in the compose window so this prevents adding > 1 images.

narrowing the window manually brings the button back

**Comment by paulmolluzzo** [comment]
@ashander FWIW, I do have a scroll in the compose when I add an image that's too large.

**Comment by ashander** [comment]
@paulmolluzzo my mistake. I just double checked and so do I. Swore I didn't before!

I'm grateful for the PR though and hope it's merged. It'll be a small UI improvement to not have to scroll

**Comment by paulmolluzzo** [comment]
If you still want the PR to go through, keep the issue open. If you really don't care or specifically don't want it, just close it again. Thanks.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/refined-twitter/commit/0d3e5dcd2d861445951fb88b596ca4c6ed9d66c6.
