### ISSUE TITLE
Keyboard shortcut to toggle "night mode"

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#28]
Suggestions for what keyboard shortcut to use welcome. It needs to be one not already used by Twitter.com or the browser.

**Comment by EliTheCoder** [comment]
I believe Ctrl+L should work for that.

**Comment by Ricardo-Silva91** [comment]
hello, I made a PR with a proposed solution for this issue (#62).
Because Ctrl+l moves the cursor to the browser address bar, I used Ctrl+m which is not used.

Feedback is welcome :smile:
