### ISSUE TITLE
Hide the "Your tweet was posted" message

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-twitter#29]
There's a "Your tweet was posted" bubble that shows in a medium gray bubble near the bottom of the screen when you send a tweet. IMO that should be in Twitter's blue color, centered, and persist for a good second or two (it's super fast now).

**Comment by sindresorhus** [comment]
Why do you even need that message? I personally prefer Unix mantra of silent on success and noisy on failure.

**Comment by paulmolluzzo** [comment]
I don't really need it, but if it's going to be there it should look nice. Want to just hide it? It's so fleeting I doubt I'll miss it.

**Comment by sindresorhus** [comment]
Ok, let's hide it then.

**Comment by paulmolluzzo** [comment]
I can't catch this thing and inspect the DOM so I can select the class. It lasts like 1 second, so if someone else wants to figure a way to put a breakpoint in there or something long enough to grab the class name then this can be done.

**Comment by sindresorhus** [comment]
@paulmolluzzo (or anyone that wants to work on this) You can put a breakpoint in the Element inspector on a DOM element whenever its subtree changes ;)

**Comment by paulmolluzzo** [comment]
@sindresorhus thanks, I'll see if I can catch it with that. I tried stepping through functions one by one after sending the tweet, but it paused on success and I saw the notification show and dismiss during the pause.
