### ISSUE TITLE
Hide promoted tweets and ads

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#3]
I wanted to add this at launch, but I never encountered a promoted tweet or ad when developing, even with my ad-blocker disabled. If anyone encounters promoted tweets or ads, please dump the HTML into a Gist and comment the link here. Or even better, do a pull request implementing this.

**Comment by elliotblackburn** [comment]
Here's the HTML of a promoted tweet, the easiest identifier seems to be in the bottom "context" class (line 261 onward).

https://gist.github.com/BlueHatbRit/75550d6af0195e3d84725d2c0c1fd6d5

If I have time this weekend I'll PR but if anyone gets to it sooner, feel free to jump on it 👍
