### ISSUE TITLE
System emoji messes with the character spacing

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/refined-twitter#30]
Examples:

![image](https://user-images.githubusercontent.com/2827047/33989558-37cd65a8-e0c8-11e7-9f3a-95c652cc20a5.png)
![image](https://user-images.githubusercontent.com/2827047/33989573-463c6c1a-e0c8-11e7-9474-4a2025bd08c1.png)
![image](https://user-images.githubusercontent.com/2827047/33989607-6068c462-e0c8-11e7-92f8-8595b95bd954.png)

Plus, the emoji aren't replaced in the text editor:
![image](https://user-images.githubusercontent.com/2827047/33989631-70c863b2-e0c8-11e7-88a6-c8bac26c9b23.png)

Gonna see if I can find the cause, but I recommend reverting to Twitter's for the time being.

**Comment by filipekiss** [comment]
I'll take a look at the spacing issue, seems to be fairly easy to address. Regarding replacing the emoji in the text editor, I've created a new issue for that. If you have any feedback, please, post on #31 instead. :)
