### ISSUE TITLE
Anatine Dark mode

### ISSUE THREAD

**Issue by dunckr** [sindresorhus/refined-twitter#32]
Thanks for making this it's awesome!

Just wondering if you would be open to adding the Anatine [Dark mode css](https://github.com/sindresorhus/anatine/blob/master/dark-mode.css) as an option to this extension?

Cheers

**Comment by paulmolluzzo** [comment]
Honestly, it would not be hard to port it over, but persistence across sessions would have to be figured. It's just a CSS file and a class on the `html`.

PR welcome!

**Comment by paulmolluzzo** [comment]
Fixed by #34
