### ISSUE TITLE
Highlight Mentions in Stream

### ISSUE THREAD

**Issue by filipekiss** [sindresorhus/refined-twitter#36]
Make tweets that mention the current user standout in the stream, like Tweetbot makes the background in a different color.

Not sure if changing the color is the best option since the user can customize how the stream looks.

**Comment by sindresorhus** [comment]
> Not sure if changing the color is the best option since the user can customize how the stream looks.

We could use the background color from `.home-tweet-box` (The tweet box at the top of the stream). It follows the user's theme.

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/sindresorhus/refined-twitter/pull/43.
