### ISSUE TITLE
Can't edit profile image with extension on

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-twitter#37]
If you click on "Edit Profile" the form that you're given on the mobile version doesn't allow editing the profile image. It's also rather ugly.

I think it might be better to black list the settings URLs and allow users to edit their profile on the desktop version since it has a richer interface.

![yucky](https://cloud.githubusercontent.com/assets/737065/15859476/4dadb728-2c93-11e6-9578-8dc892d041d9.png)

**Comment by sindresorhus** [comment]
:+1: Wanna do a PR?

**Comment by paulmolluzzo** [comment]
Yup, Thos is mostly a note to self.

**Comment by sindresorhus** [comment]
Lol. I thought you were a random user because of your new profile pic :p

**Comment by paulmolluzzo** [comment]
> Lol. I thought you were a random user because of your new profile pic :p

I am a random user.
