### ISSUE TITLE
Feature ON/OFF Switch?

### ISSUE THREAD

**Issue by ahmadawais** [sindresorhus/refined-twitter#38]
I love some features and don't like others. Which is why I end up not using this extension at all.
Would be great if you can cook in a settings page where I can switch on/off features.

**Comment by sindresorhus** [comment]
What do you hate and why? This extension is not really that opinionated yet.

**Comment by ahmadawais** [comment]
@sindresorhus Sure I can make a list.

BTW Hate might be a strong word, not a native. 

### Features I love
- [x] Simplified and improved UI.
- [x] Hides promoted tweets.
- [x] Auto-loads new tweets in the stream if you're scrolled to the top. No more clicking See 3 new Tweets!
- [x] Fixes the file extension when saving images in tweets. No more foo.jpg_large!
- [x] Embeds the photo from Instagram links directly in the tweet.
- [x] Improves scrolling performance.
- [x] Hides "Liked" tweets in the stream.
- [x] Prevents DM modal from closing when (accidentally) clicking outside the modal.
- [x] Syntax highlighting in code blocks.
- [x] Removes the annoying suggestions in the search popover.

### Features I don't like.
~~Uses the system font.~~
— Don't like the system font.
~~Replaces the Twitter emoji with native ones.~~
— I like Twitter emoji.
~~Uses the original image in tweet image galleries instead of a downsized version.~~
— Slow internet here.
~~Hides "Notifications" activity for new followers and being added to a list.~~
— I need that.

I also like the suggestion bar and trending sidebars — which helps me keep my account https://twitter.com/mrahmadawais/ up to date and get more engagement.

I hope that makes my intention clear?

**Comment by sindresorhus** [comment]
Thanks. It's always useful to know what people don't like. I don't think this extension is a good fit you, to be honest, but it shouldn't be hard to fork it and just disable the stuff you don't want.

> Uses the system font.
— Don't like the system font.

What system?

> — I like Twitter emoji.
Uses the original image in tweet image galleries instead of a downsized version.

Probably not going to be an option for this.

> Uses the original image in tweet image galleries instead of a downsized version.
— Slow internet here.

Yeah, this could be an option.

> Hides "Notifications" activity for new followers and being added to a list.
— I need that.

You don't "need", you "want". This one is objectively not essential, so probably not coming back.

> I also like the suggestion bar and trending sidebars

Those are never coming back.

**Comment by ahmadawais** [comment]
>Thanks. It's always useful to know what people don't like. 

Same here.

>I don't think this extension is a good fit you, to be honest, but it shouldn't be hard to fork it and just disable the stuff you don't want.

That's why not using it. Forking it means updating it myself. That's a scary thought 💯 but I love the code feature you just added!

>What system?

It's Macbook Pro late 2013 but I just prefer the site's original fonts. 

Anywho, thanks for taking time to answer. I appreciate that. I think that Twitter code part alone is good enough as an extension. I might fork that.

Peace! ✌️

**Comment by filipekiss** [comment]
Opened a new issue for the image replacement feature. Closing this.

**Comment by sindresorhus** [comment]
The Twitter emoji is restored now: https://github.com/sindresorhus/refined-twitter/commit/ae0bc9985fda2fd09f26b30915163c666e9eaf46

**Comment by brunolemos** [comment]
Refined Github let us disable features, any reason why Refined Twitter doesn't?
Each person has it's own preferences, so an on/off switch for each one makes sense on these kind of projects.

**Comment by brunolemos** [comment]
I would personally disable this for myself:

- Hides "Notifications" activity for new followers
- Uses your personal color theme on all profiles.
- Hides the header image on profile pages.
- Feature that is causing #111

**Comment by brunolemos** [comment]
> we’re open to a PR implementing this if you’d like to help

@jorgegonzalez ok good to know! I made it on #131

**Comment by sindresorhus** [comment]
> Uses your personal color theme on all profiles.

Why?

> Feature that is causing #111

This is not a good reason. #111 should be fixed instead.

**Comment by brunolemos** [comment]
> Why?

I like seeing other people personalizations, it shows something about their taste; similarly to the header image

>  #111 should be fixed instead.

#133

**Comment by sindresorhus** [comment]
> I like seeing other people personalizations, it shows something about their taste; similarly to the header image

I guess I don't like it as most people have absolutely no taste when it comes to colors 😝
