### ISSUE TITLE
Syntax highlighting should remove links inside code blocks

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#39]
See: https://twitter.com/tomasdev/status/953720238784303105

// @tomma5o

**Comment by jorgegonzalez** [comment]
Inline code has a similar issue:

![image](https://user-images.githubusercontent.com/12901172/40074757-846cb4fc-5848-11e8-9e32-7807e242e7bf.png)

**Comment by filipekiss** [comment]
Yeah, I'll have to look on how to implement this. I'll probably have to make inline code and code highlight work together, somehow.

**Comment by jorgegonzalez** [comment]
Working on a solution using some of the [remark](https://github.com/remarkjs/remark) packages.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
