### ISSUE TITLE
Option for force-redirect function

### ISSUE THREAD

**Issue by gslin** [sindresorhus/refined-twitter#39]
Some functions (like add user to list) are not available in mobile version.  We will need an option to disable force-redirect function.

**Comment by sindresorhus** [comment]
No need for an option. Find the URLs, and do a pull request, adding them to the blacklist: https://github.com/sindresorhus/refined-twitter/blob/aacc9edfec99cac93e5fc1b459a2cf5121eba592/extension/background.js#L3

**Comment by gslin** [comment]
It would require to blacklist all user pages (like https://twitter.com/ev this page), and I think it may not a good choice ?

**Comment by sindresorhus** [comment]
I'm gonna pass on this. This extension is optimized for the simple use-case. Most people don't use lists.
