### ISSUE TITLE
Allow a subset of Markdown

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/refined-twitter#41]
With code block support, I think it would make sense to allow a real markdown (subset).
The most common things I would use (and you can sometimes see in use on Twitter) are bold, italic, lists and inline code.

The "document"-oriented markup like headings could get abused and don't really make sense in a tweet, as well as links and images, which Twitter already handles differently.

**Comment by sindresorhus** [comment]
👍 Sounds good to me. There's already an issue for inline code block: https://github.com/sindresorhus/refined-twitter/issues/9

**Comment by sindresorhus** [comment]
If anyone wants to work on this, you can continue where https://github.com/sindresorhus/refined-twitter/pull/113 left off.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
