### ISSUE TITLE
Emoji Replacement

### ISSUE THREAD

**Issue by bardware** [sindresorhus/refined-twitter#44]
Hi,

yesterday, I installed you extension in chrome browser. I stumbled over emojies earlier and finally understand how you replace emojis with the "native ones".
There is an emoji [Women Wrestling](https://emojipedia.org/women-wrestling/). Twitter has a native icon, windows does not. The nice emoji is therefore replaced  by the emoji "Wrestlers" and the "Female" sign 
![image](https://user-images.githubusercontent.com/802702/35124476-880f174c-fca6-11e7-86e6-942e6771f3f7.png)
This does not look so nice.

**Comment by filipekiss** [comment]
@sindresorhus should we use native emoji on Mac only to avoid things like this? I don't think we can detect if the system supports that emoji since it's basically just the two unicodes combined and would result in a false positive (but I may be wrong, I don't know that much about emoji :P)

**Comment by sindresorhus** [comment]
> should we use native emoji on Mac only to avoid things like this?

Yes, I don't want to deal with dumb Windows stuff.

**Comment by filipekiss** [comment]
@sindresorhus Great! I'll make a PR soon fixing this, then!
