### ISSUE TITLE
Some suggestions about Refining Twitter (being true to the brand) more than forcing the mobile site...

### ISSUE THREAD

**Issue by Mancerrss** [sindresorhus/refined-twitter#45]
I like your extension atually, it gives ability to run the Twitter in mobile mode, restore down the tab window and snap in on the side while working. Before it wasn't entirely possible (desktop Twitter is horrible in responsive design) but now it is now because of this extension. However, forcing you to run Twitter always in mobile site removes, few things I always loved about Twitter desktop webiste, the auto tweet refresh, video, Vines and GIFs autoplay, ability to see Trends at the side, who to follow at the side, my profile overview, tweet expanding in a window instead of a new link, new tweet in a window and others because Twitter mobile is an entirely different website and stylesheet

I don't know if you just made this simple extension to always ridirect you to mobile site because Twitter desktop website lags on your device or if you can do more about this but what if you stay true about your extension brand "Refined Twitter"

What if you update this extension, to merge the stylesheet of mobile site to the desktop site, that it will switch to mobile UI when scaled down in a very least, but please always keep the splash screen at the beginning even on desktop website (just when going in the everytime in the Home) or going in for the first time on Twitter website on the tab, or another option to just completely run always the mobile UI or redirect. 

Beyond that first inital suggested update, there is so much more improvements you can make to really expand the capabilities of this extension like always load Instagram photos, trend ordered in numbers, always show number of tweets in trends, always show tick numbers of replies, arrows to switch recent trend locations, disable things and other more improvement only you can fathom

Please continue to work on this great extension, Thank you and keep innovating

**Comment by sindresorhus** [comment]
In hindsight you're are absolutely right. Had I done it again, I would have definitely started with the desktop site and improved it from there. Oh well...

Doesn't matter anyways. This extension is now deprecated: https://github.com/sindresorhus/refined-twitter/blob/master/readme.md#deprecated
