### ISSUE TITLE
Save image when there are multiple images in a tweet

### ISSUE THREAD

**Issue by bardware** [sindresorhus/refined-twitter#48]
Hi,

when there is one image in a tweet and I click `Save image`in the context menu the image is saved with the correct extension.
When there are multiple images I can only select "Save as" in the context menu and Chrome saves `.html` files. 
Can you make it possible to save each single images out of the four allowed?

Best,
Bernhard

**Comment by sindresorhus** [comment]
Do you have a tweet we can reproduce with?

**Comment by bardware** [comment]
I have this [tweet](https://twitter.com/adriana_lowe/status/957550859067551745)
I just realize when I see the tweet I can right click each single image and save the image. It does not work when I click the image to see it completely.

**Comment by piotrmil** [comment]
yeah, I agree, this would be super-useful.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
