### ISSUE TITLE
Option to disable useNativeEmoji

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-twitter#49]
😜

What do you have against Twitter's emoji?

I'm so sick of Apple's emoji, they still rock the 2000 OS X [Aqua style](https://www.google.com/search?q=apple+aqua+style&tbm=isch) and they're everywhere 😅 

I feel that there should be an option to set Google's Blob Emojis <sup><sup>/ s</sup></sup>

<img src="https://user-images.githubusercontent.com/1402241/35848656-72d88e26-0b51-11e8-8757-20576ea452e4.png" width=200>

They're also smaller:

<img width="481" alt="native vs Twitter" src="https://user-images.githubusercontent.com/1402241/35849977-ed1af1a2-0b55-11e8-9ce0-94c0bb9bc603.png">

**Comment by fregante** [comment]
Related bug caused by this feature: #44 

In all honesty I'd be more than fine if this was reversable via CSS (e.g. if the old emoji element was simply hidden with `display: none`)

**Comment by sindresorhus** [comment]
I think we should just remove the feature. It's not very important to me and it seems that a lot of people prefer the Twitter-style emoji. @filipekiss Thoughts?

**Comment by filipekiss** [comment]
No objections. I kinda like Twitter-style emojis too.

**Comment by felixfbecker** [comment]
I came here to file a feature request for replacing Twitter emoji with native emoji to find out it used to do that and then it was removed 😢 
Could we get this back, behind an option? I don't want every app to have different emoji styles. Also not everyone uses a mac. Windows' native emoji set looks dope

**Comment by sindresorhus** [comment]
Sure, if you want to do the work. With the new Twitter refresh coming soon, I'm just not sure it's worth investing the time in this.
