### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#5]
The only thing I'm missing from the desktop version is Cmd+Enter to submit. Should be easy to add.

Pull request appreciated :)

**Comment by jdcaballerov** [comment]
also n for new and gs to change tab ;)

**Comment by growth-austen** [comment]
I also wish that tapping things (e.g. liking a tweet) would deselect after it selected

**Comment by ashander** [comment]
+1 would make this perfect. another request: Enter to send a DM

**Comment by sindresorhus** [comment]
Alright. I added a bunch of shortcuts: https://github.com/sindresorhus/refined-twitter#keyboard-shortcuts Let me know if you're missing any. I only want to add what people actually use.

**Comment by sindresorhus** [comment]
@growth-austen Not exactly sure what you're asking for. Can you clarify?

**Comment by paulmolluzzo** [comment]
@sindresorhus Nice! But why are you clicking the element instead of changing the URL directly? For instance, if you change the URL you can compose a new tweet from anywhere. With the current `click` method you can't compose a tweet from messages (nor can you make a new DM, which actually makes more sense).

**Comment by sindresorhus** [comment]
@paulmolluzzo Changing the URL redirects to the new URL instead of just changing the React state, like clicking does, causing a flash and loss of state.

**Comment by gonzaloserrano** [comment]
I'd love a vim-like shortcut like j/k for next/prev tweet, like e.g gmail does

**Comment by sindresorhus** [comment]
@gonzaloserrano Definitely something I'd like to see added. Would appreciate a PR. https://github.com/sindresorhus/refined-twitter/issues/10

**Comment by callumlocke** [comment]
When viewing a photo (modal overlay), it would be good to be able to press Escape to close it

**Comment by paulmolluzzo** [comment]
@gonzaloserrano I've made a PR that address your request: #19

**Comment by sindresorhus** [comment]
@callumlocke See https://github.com/sindresorhus/refined-twitter/pull/23.

**Comment by sindresorhus** [comment]
Closing this as everything mentioned is resolved. For additional requests, open a new issue.
