### ISSUE TITLE
Better profile pages

### ISSUE THREAD

**Issue by tj** [sindresorhus/refined-twitter#5]
First of all thanks for starting this! Maybe it's just me but I'd like the profile pages to show almost nothing, just the avatar, bio and tweets. The avatar could be up top and center, replacing the weird geocities-inspired  background thingies

**Comment by sindresorhus** [comment]
I would remove the huge header too. Can you be a bit more specific about what else you would remove?

**Comment by tj** [comment]
I'm not 100% sure, I had an idea in my head, I'll send over a PR and some screens if I come up with anything decent haha

**Comment by filipekiss** [comment]
Hey @imaginamundo, take a look at this. You may be interested in giving us some ideas.

**Comment by jorgegonzalez** [comment]
Do we want to keep this issue open?

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
