### ISSUE TITLE
Center the navbar widgets

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#57]
Having them on the edges made sense when Twitter filled the whole page, but this extension removes those boxes on the side of the feed, so there's no longer any good reason to keep the navbar widgets at the edges. Thoughts?

#### Before

 
<img width="1405" alt="screen shot 2018-02-16 at 01 39 32" src="https://user-images.githubusercontent.com/170270/36274435-5865e366-12ba-11e8-9f13-58eefb3c4935.png">

#### After

<img width="1405" alt="screen shot 2018-02-16 at 01 39 25" src="https://user-images.githubusercontent.com/170270/36274456-5f13ffc2-12ba-11e8-8998-914b42aad3b9.png">

**Comment by Miklet** [comment]
What about loading indicator that shows up on the center of navbar? 🤔 Beside that I am neutral 😅 Btw. if you shrink your browser the elements of navbar are centering so styles already exists, it is only matter of applying them to wider media query.

**Comment by sindresorhus** [comment]
@Miklet The loading indicator could just be moved somewhere else.

The change itself is very simple:

```css
.global-nav .container {
	max-width: 820px !important;
}
```

**Comment by gdad-s-river** [comment]
It makes sense to center the navbar widgets. Would the spinner at the left of Home widget make sense?

I'd like to start taking up some issues, starting with this small one. I've only worked a year as a junior front end dev after which I quit, and it's after a long time that I'm touching anything code-y to make a comeback to learn things and eventually get a job, I'd really appreciate if I could do this right with some help.

@sindresorhus

**Comment by filipekiss** [comment]
@gdad-s-river Give it a go! Fork it and make a pull-request and we'll happily review it and point you in the right direction!
