### ISSUE TITLE
Hashtag autocomplete doesn't work

### ISSUE THREAD

**Issue by mantovanig** [sindresorhus/refined-twitter#59]
When I'm writing a new tweet after type "#" and some character the native twitter autocomplete with suggestion for hashtag doesn't appear.

Details:
macOS High Sierra 10.13.1
Chrome 63
Refined Twitter 18.2.15.1841

**Comment by sindresorhus** [comment]
It was removed by accident in https://github.com/sindresorhus/refined-twitter/commit/ed0c33a835ecbcff2f1e85bfe56f5847582d40a7 Should be back now.

**Comment by mantovanig** [comment]
Thanks!!
