### ISSUE TITLE
Consider using hard coded CSS assets to prevent tracking

### ISSUE THREAD

**Issue by jonathanKingston** [sindresorhus/refined-twitter#6]
So the extension didn't work in Firefox the first time for me mostly because I had tracking protection on by default.

![selection_146](https://cloud.githubusercontent.com/assets/338988/15031105/6895be64-124e-11e6-9a75-9e32df59315d.png)

Would you consider hard coding the CSS files in and blocking the default ones?

**Comment by sindresorhus** [comment]
No, that would be a maintenance nightmare. Can't you just whitelist those URLs?

**Comment by jonathanKingston** [comment]
Thought you might say that. I'm not sure that is possible through the extension API.

I'm pretty sure there isn't even a way to whitelist these through Firefox once it is on. I'll look into that :)
