### ISSUE TITLE
Options not loading

### ISSUE THREAD

**Issue by shanegriffiths** [sindresorhus/refined-twitter#60]
![image](https://user-images.githubusercontent.com/652339/36318675-7d0a56c4-1338-11e8-83cd-6914bf897d46.png)

Can someone help with this?
Using Chrome: Version 65.0.3325.73 (Official Build) beta (64-bit)

**Comment by shanegriffiths** [comment]
Or is this the desired functionality? @sindresorhus

**Comment by sindresorhus** [comment]
That's intentional. It's there in case we want to add options, but there are no options yet.
