### ISSUE TITLE
Keyboard shortcut for night mode mutes tab in Firefox

### ISSUE THREAD

**Issue by Miklet** [sindresorhus/refined-twitter#64]
Hi

PR #62 added a keyboard shortcut for turning on a night mode but in Firefox 58.0.2 (not sure if also not in earlier versions) this shortcut is reserved for muting a tab.

Cheers.

**Comment by sindresorhus** [comment]
// @Ricardo-Silva91

**Comment by filipekiss** [comment]
Hey @Ricardo-Silva91, what do you think we change the night mode toggle Keyboard shortcut to <kbd>Alt</kbd><kbd>m</kbd>? This way the chances of conflicting with a browser shortcut is lower

**Comment by Miklet** [comment]
Oh so sorry, I had build version loaded and it wasn't working but when I installed version from the Chrome store it works but still mutes tab.
