### ISSUE TITLE
Preserve text in input field in messages

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#65]
If you accidentally click outside the messages modal, your unsent message is lost. It happened a lot to me, so I added a prevention here so that the modal would only close on clicking `X` and not outside. Some people find this annoying though, so we should solve it the correct way by preserving the text when they go back to messages.

**Comment by arunsathiya** [comment]
I would definitely +1 on this. I don't write code. Hope to see this come to life one day.

**Comment by gdad-s-river** [comment]
@filipekiss, @sindresorhus I'll work on this.

**Comment by sindresorhus** [comment]
Awesome! :)

**Comment by filipekiss** [comment]
@gdad-s-river Can you link to a branch or commit where I can look at what you've done so far and see if I can help?

**Comment by gdad-s-river** [comment]
@filipekiss I've been able to make it work. I'll clean up the code a bit, and comment here then to get feedback. Also would writing tests for this a good idea? I've never written any kind of tests before.

**Comment by filipekiss** [comment]
@gdad-s-river Testing browser interaction is kinda of a pain and this issue is basically browser interaction. I don't see the need to write tests for this, at least for now.

**Comment by gdad-s-river** [comment]
Hi @filipekiss! I'm ready to make a pull request. However I have to ask if I should rebase the commits to one? Or should I keep them [as is](https://github.com/gdad-s-river/refined-twitter/commits/feature/65)

**Comment by gdad-s-river** [comment]
@filipekiss https://github.com/sindresorhus/refined-twitter/pull/83
