### ISSUE TITLE
Incorrect vertical offset when scrolling with J and K key

### ISSUE THREAD

**Issue by ksaitor** [sindresorhus/refined-twitter#66]
![feb-17-2018 20-15-54](https://user-images.githubusercontent.com/936436/36340844-a799499e-141f-11e8-89a8-7acd688a53e4.gif)

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
