### ISSUE TITLE
Remove the Moments button

### ISSUE THREAD

**Issue by anaisbetts** [sindresorhus/refined-twitter#7]
![image](https://user-images.githubusercontent.com/1396/33736605-3a830d0a-db61-11e7-9042-4f30df6cd83a.png)

**Comment by sindresorhus** [comment]
Weird, I don't have that button. Can you share the selector to hide it?

**Comment by anaisbetts** [comment]
`li.moments` should be sufficiently conservative. Do you also have other extensions that modify Twitter running? I noticed in screenshots you also have a button that I don't:

![image](https://user-images.githubusercontent.com/1396/33737020-b9f353aa-db62-11e7-82d6-46686b3e7abb.png)

**Comment by dumitruaxentii** [comment]
@paulcbetts that's the Buffer extension.

**Comment by sindresorhus** [comment]
> Do you also have other extensions that modify Twitter running? I noticed in screenshots you also have a button that I don't:

Yes, I forgot to disable the Buffer extension.

**Comment by anaisbetts** [comment]
:bow:, thanks for the fix
