### ISSUE TITLE
Add the ability to right-click download images in gallerys

### ISSUE THREAD

**Issue by kurtextrem** [sindresorhus/refined-twitter#70]
See e.g. here: https://twitter.com/redrawnoxen/status/965701135431618560
You can't right-click save the image as the arrows are in front (we probably need to resize them so they don't take as much space)

**Comment by sindresorhus** [comment]
👍

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
