### ISSUE TITLE
Investigate replacing jQuery Slim with vanilla or Sprint

### ISSUE THREAD

**Issue by kurtextrem** [sindresorhus/refined-twitter#71]
See https://github.com/kitten/sprint, performance much higher.
Also, is jQuery / Sprint even needed? Most I've seen in refined twitter (not sure about refined Github) seems like it could be easily done without jQ.

**Comment by sindresorhus** [comment]
I used jQuery for developer happiness. The DOM is still annoying to deal with in vanilla JS. I've tried using Sprint before. It was too buggy.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
