### ISSUE TITLE
Not loading tweets

### ISSUE THREAD

**Issue by drepram** [sindresorhus/refined-twitter#77]
The normal twitter always have another tweet at the bottom of feed so the users wouldn't stop scrolling.

Is this a bug?

![screen shot 2018-03-05 at 10 01 26](https://user-images.githubusercontent.com/34530026/36955682-75b8f3a4-205c-11e8-80d4-6dd8956dccc5.png)

**Comment by Hoishin** [comment]
I can scroll down just like without the plugin. Repro process would help.

**Comment by kurtextrem** [comment]
This sometimes happens here too, but I think this is a Twitter issue (or maybe browser) as I couldn't find any wrong CSS

**Comment by jorgegonzalez** [comment]
I would suggest you try reproducing this issue in incognito mode, i.e. with all other extensions off.

**Comment by drepram** [comment]
I thought I've closed this issue, the extension works as it should. There is no bug.
