### ISSUE TITLE
Support Chrome 49 and lower

### ISSUE THREAD

**Issue by prusnak** [sindresorhus/refined-twitter#8]
Requirement of Chrome 50 seems arbitrary. It would be better to use version which introduced the API needed to run the extension.

**Comment by sindresorhus** [comment]
Why? Chrome 50 is the latest and the one I've tested on.

**Comment by paulmolluzzo** [comment]
Relevant: https://kangax.github.io/compat-table/es6/ This table doesn't show Chrome 49 until you click "Show Obsolete"

**Comment by jamen** [comment]
I tried updating Chromium to v50, but it doesn't seem to work.  I think v49 is the latest Chromium release.

**Comment by dmitriz** [comment]
[Chrome stopped updating for Mac OSX 10.8 and below with 49 being the last version.](https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html)

[It seems still possible to install Chrome 50 on 10.8 with a 6-step process](http://apple.stackexchange.com/a/237289/56300).
But I imagine those will look intimidating for some folks.

Why not upgrade OSX? Lack of time and trust to Apple for not breaking things that worked just fine? ;)

**Comment by sindresorhus** [comment]
I'm going to say decline this, sorry. I have not tested the extension on Chrome 49 and I'm not going to. When Chrome 51 is out we're gonna target that as it brings in some nice improvements. You can manually install and change the requirement, but no guarantees it will work in the future.
