### ISSUE TITLE
Remove custom color on user profiles

### ISSUE THREAD

**Issue by Hoishin** [sindresorhus/refined-twitter#89]
Night mode is cool but sometimes it looks really bad with certain custom user colours.

For example:
![screen shot 2018-03-26 at 11 34 48](https://user-images.githubusercontent.com/28832095/37884218-d7e227ba-30e9-11e8-8a67-c045c00dd98d.png)

A similar but more night-mode-friendly colours for night mode would be nice to have in this extension.

**Comment by sindresorhus** [comment]
Another alternative would be to remove custom colors and just apply good-looking colors, always.

**Comment by Hoishin** [comment]
I don't know if it is the best to replace the custom colours since some people put their colours for reasons (I guess). But also logics for optimising colours for human sense would be too complicated. I know an extension that does it though, so not entirely impossible.

**Comment by sindresorhus** [comment]
Profile pages having custom colors is IMHO just annoying. I'd be happy to merge a PR removing profile custom colors, and using your own colors instead.
