### ISSUE TITLE
Improve Notifications Layout

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-twitter#9]
The list of notifications is really inconsistent in the way the left column of icons/avatars are displayed. Maybe we can standardize the layout a bit by moving the avatar of the "actor" (the retweeter or liker) to the left column and then overlaying the action as a badge?

Current:

![screen shot 2016-05-04 at 10 40 10 pm](https://cloud.githubusercontent.com/assets/737065/15035015/b23c64f4-124a-11e6-95aa-459365a58c11.png)

Rough Mock of New Idea:

![screen shot 2016-05-04 at 10 50 24 pm](https://cloud.githubusercontent.com/assets/737065/15035026/b91c31e6-124a-11e6-926b-2eb9a6301a3b.png)

**Comment by sindresorhus** [comment]
👍 Sounds good. I would also make the avatars a bit smaller in general.

**Comment by jacobbearden** [comment]
So I've been looking into doing this, and have a couple questions:

When there's more than one "actor" (ie. "**TempCFO Los Angeles** and 4 others followed you" in the picture) should it move the first image to the left column, and leave the others?

The "icon" on the SVG's is just transparency, which could easily make it hard to see on certain images, and if I just set a `background color`/`border-radius` (black just as an example) it ends up looking like this:

![screenshot from 2016-06-03 00 40 51](https://cloud.githubusercontent.com/assets/5340692/15770852/de6dca0a-2923-11e6-808a-ae1d442f147f.png)

So will altering the SVG itself be necessary? I'm not very familiar with SVG's.

**Comment by paulmolluzzo** [comment]
> When there's more than one "actor" (ie. "TempCFO Los Angeles and 4 others followed you" in the picture) should it move the first image to the left column, and leave the others?

That sounds right. You could also try to "stack" them one on top of the other on the left column too.

> The "icon" on the SVG's is just transparency, which could easily make it hard to see on certain images, and if I just set a background color/border-radius (black just as an example) it ends up looking like this:

I would use white instead, and clean up the dimensions/radius to make it a perfect circle, but that's about right too. The border is also a little thick, you only need `1px` so if the avatar and icon are the same color there is a distinction. I don't think you'll need to alter the `svg` itself, just style it with CSS.

**Comment by sindresorhus** [comment]
@paulmolluzzo Is there anything more to do with this issue?

**Comment by paulmolluzzo** [comment]
@sindresorhus sorry for the late reply. Originally I wanted to see the avatars on the left side when someone liked or RT'd a tweet to match the layout of the timeline like this:

![](https://cloud.githubusercontent.com/assets/737065/15035026/b91c31e6-124a-11e6-926b-2eb9a6301a3b.png)

I'm not sure if that idea is supported though. The avatar shrinking was just another idea that was brought up in this thread but not the original idea.

**Comment by sindresorhus** [comment]
Not worth the effort I think.
