### ISSUE TITLE
Style text in backticks with monospaced font

### ISSUE THREAD

**Issue by southpolesteve** [sindresorhus/refined-twitter#9]
Aany tweet text wrapped in ` should get styled as a monospaced font

**Comment by sindresorhus** [comment]
👍 Also 3-backtick code blocks.

**Comment by sindresorhus** [comment]
@southpolesteve Still interested in working on this? No worries if not :)

**Comment by southpolesteve** [comment]
Currently on vacation for a couple weeks. Happy to let someone else run with it.
