### ISSUE TITLE
Opera bugs?

### ISSUE THREAD

**Issue by EC-O-DE** [sindresorhus/refined-twitter#90]
Seems that this is buggy with Opera?

Can't get Twitter to look like on the sample images... :/

**Comment by sindresorhus** [comment]
You're going to have to be more specific than that.

**Comment by EC-O-DE** [comment]
Twitter pages looks almost the same as always - those top "menu buttons" got centered.. But I'm not getting that sleek and compact tweet-list like in your sample image.

**Comment by sindresorhus** [comment]
Happy to receive PRs fixing things in (latest) Opera, but I don't have time to fix things for it. It's based on Chromium, so things should *just work* (in theory).
