### ISSUE TITLE
Clicking links in tweet modals does not open them

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/refined-twitter#94]
Clicking, middle-clicking, cmd-clicking links inside tweets while in a modal window does not open them. Works fine in the timeline/home view.

**Comment by jorgegonzalez** [comment]
[This](https://github.com/sindresorhus/refined-twitter/blob/master/source/content.js#L17) is the culprit.

**Comment by filipekiss** [comment]
I just tried this and it's working fine. Can you provide more details?

**Comment by filipekiss** [comment]
It worked just fine. Using the latest version from the extension.

![untitled](https://user-images.githubusercontent.com/48519/38255539-72aa7466-3732-11e8-9143-fbfde949bbe3.gif)

First one is middle click and second one is <kbd>⌘</kbd>+click

**Comment by sindresorhus** [comment]
I've encountered this too.

**Comment by filipekiss** [comment]
Does the console reports anything? I'm unable to reproduce this issue :(

```
Chrome Version: 65.0.3325.181 (Official Build) (64-bit)
macOS Version: 10.13.3 (17D102)
Refined Twitter: compiled directly from the master branch
```

**Comment by filipekiss** [comment]
Okay, so I got the hang of this: If I open the link to the tweet directly, it works as expected. If I open the tweet details from the timeline, that's when it seems to break. I'll take a look to see if I can find the culprit. Thanks for the info, guys.

**Comment by ivancuric** [comment]
https://www.youtube.com/watch?v=lHHUClcInUg

**Comment by filipekiss** [comment]
The culprit is commit 0b6e6622. I'll try to fix this withouth removing the functionality.

**Comment by filipekiss** [comment]
This commit is also responsible for #98
