### ISSUE TITLE
When opening one of my list, can't access members

### ISSUE THREAD

**Issue by borisschapira** [sindresorhus/refined-twitter#95]
Hello!

First of all, thank you very much for your work. I'm a proud patreon but sometimes, words count as much as money so, really, thanks.

The bug: when I open one of my lists with Refined Twitter activated, I can't consult the list of members. Example: https://twitter.com/borisschapira/lists/front-webperf

**Comment by sindresorhus** [comment]
Yeah, we should not hide the sidebars when on a list view.

Not sure if there's any way to handle that with just CSS. We might have to inject some JS to disable these styles when on a list:

https://github.com/sindresorhus/refined-twitter/blob/a8403f5fe552e793ab62fae6404fcd964c5e12e6/source/style/content.css#L78-L82

**Comment by sindresorhus** [comment]
@filipekiss @jorgegonzalez Any ideas?
